version: '3.9'
services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: app-container
    hostname: web-server
    ports:
     - "8080:8080"
    tty: true
  db:
    image: postgres:12.0
    container_name: db-container
    build:
      context: .
      # command: docker cp ./dockerDB/init.sql db-container:/docker-entrypoint-initdb.d/
    tty: true
    environment:
      POSTGRES_USER: yamadatarou
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: line_bot
    hostname: db-server
    ports:
      - "5432:5432"
